# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: history.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='history.proto',
  package='history',
  syntax='proto3',
  serialized_options=b'\252\002\017history_service',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rhistory.proto\x12\x07history\"O\n\x16\x41\x64\x64OrderHistoryRequest\x12\x0f\n\x07orderId\x18\x01 \x01(\t\x12\x14\n\x0c\x63ustomerName\x18\x02 \x01(\t\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x03\"8\n\x14\x41\x64\x64OrderHistoryReply\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"b\n\x19\x43\x61ncelOrderHistoryRequest\x12\x0f\n\x07orderId\x18\x01 \x01(\t\x12\x14\n\x0c\x63ustomerName\x18\x02 \x01(\t\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x03\x12\x0e\n\x06reason\x18\x04 \x01(\t\";\n\x17\x43\x61ncelOrderHistoryReply\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xbc\x01\n\x07History\x12S\n\x0f\x41\x64\x64OrderHistory\x12\x1f.history.AddOrderHistoryRequest\x1a\x1d.history.AddOrderHistoryReply\"\x00\x12\\\n\x12\x43\x61ncelOrderHistory\x12\".history.CancelOrderHistoryRequest\x1a .history.CancelOrderHistoryReply\"\x00\x42\x12\xaa\x02\x0fhistory_serviceb\x06proto3'
)




_ADDORDERHISTORYREQUEST = _descriptor.Descriptor(
  name='AddOrderHistoryRequest',
  full_name='history.AddOrderHistoryRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='orderId', full_name='history.AddOrderHistoryRequest.orderId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='customerName', full_name='history.AddOrderHistoryRequest.customerName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='amount', full_name='history.AddOrderHistoryRequest.amount', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=105,
)


_ADDORDERHISTORYREPLY = _descriptor.Descriptor(
  name='AddOrderHistoryReply',
  full_name='history.AddOrderHistoryReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='history.AddOrderHistoryReply.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='history.AddOrderHistoryReply.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=107,
  serialized_end=163,
)


_CANCELORDERHISTORYREQUEST = _descriptor.Descriptor(
  name='CancelOrderHistoryRequest',
  full_name='history.CancelOrderHistoryRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='orderId', full_name='history.CancelOrderHistoryRequest.orderId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='customerName', full_name='history.CancelOrderHistoryRequest.customerName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='amount', full_name='history.CancelOrderHistoryRequest.amount', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='reason', full_name='history.CancelOrderHistoryRequest.reason', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=165,
  serialized_end=263,
)


_CANCELORDERHISTORYREPLY = _descriptor.Descriptor(
  name='CancelOrderHistoryReply',
  full_name='history.CancelOrderHistoryReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='history.CancelOrderHistoryReply.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='history.CancelOrderHistoryReply.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=265,
  serialized_end=324,
)

DESCRIPTOR.message_types_by_name['AddOrderHistoryRequest'] = _ADDORDERHISTORYREQUEST
DESCRIPTOR.message_types_by_name['AddOrderHistoryReply'] = _ADDORDERHISTORYREPLY
DESCRIPTOR.message_types_by_name['CancelOrderHistoryRequest'] = _CANCELORDERHISTORYREQUEST
DESCRIPTOR.message_types_by_name['CancelOrderHistoryReply'] = _CANCELORDERHISTORYREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AddOrderHistoryRequest = _reflection.GeneratedProtocolMessageType('AddOrderHistoryRequest', (_message.Message,), {
  'DESCRIPTOR' : _ADDORDERHISTORYREQUEST,
  '__module__' : 'history_pb2'
  # @@protoc_insertion_point(class_scope:history.AddOrderHistoryRequest)
  })
_sym_db.RegisterMessage(AddOrderHistoryRequest)

AddOrderHistoryReply = _reflection.GeneratedProtocolMessageType('AddOrderHistoryReply', (_message.Message,), {
  'DESCRIPTOR' : _ADDORDERHISTORYREPLY,
  '__module__' : 'history_pb2'
  # @@protoc_insertion_point(class_scope:history.AddOrderHistoryReply)
  })
_sym_db.RegisterMessage(AddOrderHistoryReply)

CancelOrderHistoryRequest = _reflection.GeneratedProtocolMessageType('CancelOrderHistoryRequest', (_message.Message,), {
  'DESCRIPTOR' : _CANCELORDERHISTORYREQUEST,
  '__module__' : 'history_pb2'
  # @@protoc_insertion_point(class_scope:history.CancelOrderHistoryRequest)
  })
_sym_db.RegisterMessage(CancelOrderHistoryRequest)

CancelOrderHistoryReply = _reflection.GeneratedProtocolMessageType('CancelOrderHistoryReply', (_message.Message,), {
  'DESCRIPTOR' : _CANCELORDERHISTORYREPLY,
  '__module__' : 'history_pb2'
  # @@protoc_insertion_point(class_scope:history.CancelOrderHistoryReply)
  })
_sym_db.RegisterMessage(CancelOrderHistoryReply)


DESCRIPTOR._options = None

_HISTORY = _descriptor.ServiceDescriptor(
  name='History',
  full_name='history.History',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=327,
  serialized_end=515,
  methods=[
  _descriptor.MethodDescriptor(
    name='AddOrderHistory',
    full_name='history.History.AddOrderHistory',
    index=0,
    containing_service=None,
    input_type=_ADDORDERHISTORYREQUEST,
    output_type=_ADDORDERHISTORYREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='CancelOrderHistory',
    full_name='history.History.CancelOrderHistory',
    index=1,
    containing_service=None,
    input_type=_CANCELORDERHISTORYREQUEST,
    output_type=_CANCELORDERHISTORYREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_HISTORY)

DESCRIPTOR.services_by_name['History'] = _HISTORY

# @@protoc_insertion_point(module_scope)
